Add informative text about raising an exception…
w3c/rdf-canon pull request #189
Opened 2023-11-28 21:31 UTC by gkellogg

… and terminating early if a poison dataset is detected.

Fixes #186.

2023-11-28 21:35 UTC, TallTed requested changes
matching plural/singular things

2023-11-28 21:35 UTC, TallTed commented on spec/index.html
> +      into a <a>canonicalized dataset</a> or raise an error if
```suggestion
      into a <a>canonicalized dataset</a> or raises an error if
```

2023-11-28 21:35 UTC, TallTed commented on spec/index.html
> +        by raising a suitable exception and terminating early.
```suggestion
        by raising suitable exceptions and terminating early.
```

2023-11-28 22:05 UTC, jyasskin approved these changes
Thanks!

2023-11-28 22:05 UTC, jyasskin commented on spec/index.html
> +        Implementations MUST prevent against potential denial-of-service attacks
This predates this PR, but something's wrong with "prevent against".
```suggestion
        Implementations MUST defend against potential denial-of-service attacks
```

2023-11-28 22:48 UTC, dlongley approved these changes

2023-11-29 08:39 UTC, yamdan approved these changes
Thanks!

2023-11-29 10:28 UTC, iherman approved these changes

2023-11-29 10:29 UTC, iherman commented
The echidna action file must be updated before merge: "WD" -> "CRD"

2023-11-29 20:24 UTC, merged

2023-11-29 20:47 UTC, TallTed commented
>> [@iherman] The echidna action file must be updated before merge: "WD" -> "CRD"

> Echidna Auto-publish WD

Seems to say the echidna action file has not been updated?

2023-11-29 21:38 UTC, gkellogg commented
That was something @pchampin was going to look into.

2023-11-30 10:46 UTC, deniak commented
That said, trying to publish a WD from a CRS will be rejected by echidna.

2023-11-30 10:56 UTC, pchampin commented
@ivan @gkellogg 
As pointed out by @deniak, Echidna is currently disabled (by commenting out the token).
The "page build and deployment" action still runs he checks, and skips the publishing on TR.
We can still publish new Editors' Drafts, but they are now out of sync with TR.

I hope the action will kick-in again when I update the Echidna config, otherwise, I believe I can re-run it manually.

2023-11-30 11:09 UTC, iherman commented
Ah! I missed the commenting trick. I usually rename the yml file in similar circumstances...

2023-11-30 11:15 UTC, pchampin commented
I have updated the Echidna config, and I had to make a dummy commit to spec/index.html to get the action to run, but we now have a new CR draft : https://www.w3.org/TR/2023/CRD-rdf-canon-20231130/