Add Test Report for Java Corese
w3c/rdf-canon pull request #206
Opened 2024-03-06 16:53 UTC by remiceres

Hello,

I've added a new test report for the Java [Corese](https://github.com/Wimmics/corese/) implementation of RDF-CANON. 
Please let me know if any further modifications are needed.

Thank you

2024-03-06 16:59 UTC, gkellogg requested changes
Looks like the GH Action wasn't able to parse your report. You might try running `rake` in the `/reports` directory (after doing a `gem install`). Once it runs cleanly, and `reports/index.html` meets your expectations, you can commit your EARL report along with the associated generated files.

2024-03-07 08:45 UTC, remiceres commented
Thank you for your feedback. I have corrected the errors in my report and have now successfully executed the rake command locally.

2024-03-07 22:28 UTC, gkellogg commented
This reviewed a bug in the earl-report gem, which creates invalid Turtle in earl.ttl. I'll fix that in a followup PR.

2024-03-07 22:29 UTC, gkellogg approved these changes

2024-03-07 22:29 UTC, merged