Change "issued identifiers list" to "issued identifiers map".
w3c/rdf-canon pull request #39
Opened 2022-11-22 22:06 UTC by gkellogg

Fixes #36.

2022-11-22 22:53 UTC, gkellogg commented on spec/index.html
> +      <dd>A <a data-cite="INFRA#ordered-map">map</a> that relates existing identifiers to issued identifiers,
```suggestion
      <dd>An <a data-cite="INFRA#ordered-map">ordered map</a> that relates existing identifiers to issued identifiers,
```

2022-11-22 22:57 UTC, dlongley approved these changes
Thanks! I didn't look closely to see if we missed any other occurrences. See my suggestion for a typo fix.

2022-11-22 22:57 UTC, dlongley commented on spec/index.html
> +          <a data-cite="INFRA#map-entryå">map entry</a> for <var>existing identifier</var> in
```suggestion
          <a data-cite="INFRA#map-entry">map entry</a> for <var>existing identifier</var> in
```

2022-11-23 13:33 UTC, yamdan requested changes
Thank you @gkellogg, I added only small suggestion for a typo fix.

2022-11-23 13:33 UTC, yamdan commented on spec/index.html
> +        <li id="iia-3">Add a <a data-cite="INFRA#map-entry">entry</a>
```suggestion
        <li id="iia-3">Add an <a data-cite="INFRA#map-entry">entry</a>
```

2022-11-23 18:27 UTC, merged