Rename `_:b*` to `_:e*` in the test 57 (seems to be forgotten in #56)
w3c/rdf-canon pull request #75
Opened 2023-02-01 08:00 UTC by yamdan

This is merely additional patching related to #56, where test 057 has remained with its old `_:b*` labels.

2023-02-01 08:41 UTC, iherman commented
I believe that was actually intentional. The idea was to have a test does use `_:b` to prove that the implementation doesn't get confused by those and the nodes ids provided by the algorithm.

2023-02-01 09:04 UTC, yamdan commented
Thanks. Then, I should have left `_:g` as it was, whereas I think the subject `_:b1` should still be replaced with `_:e0`.

2023-02-01 18:10 UTC, dlongley commented
Yeah, we want to have one or more tests with inputs that start with blank node labels that are used internally in the algorithm (i.e., that start with `b`) to ensure an implementation can handle that properly.

2023-02-01 22:24 UTC, gkellogg requested changes
Agreed, we shouldn't merge this PR, as that naming is intentional.

2023-02-02 02:01 UTC, yamdan commented
I thought such an intention (test with `_:b*`) was already expressed as test063 instead of this test057. Nevertheless, having more than one such test case is fine, so that I will withdraw this PR.

2023-02-02 02:01 UTC, closed without merging