Add privacy/security notes to specification.
w3c/rdf-canon pull request #77
Opened 2023-02-01 17:04 UTC by msporny

This PR adds a few privacy/security notes to the specification as issues... the issues will need to be refined into specification text.

2023-02-01 17:48 UTC, gkellogg commented
The Echidna failure with undefined terms is unrelated to this PR and likely due to some change in infrastructure which requires further investigation.

2023-02-01 17:50 UTC, gkellogg requested changes
Can we reference specific issues on the repo using `data-number`? If we don't have existing issues, they should be created anyway.

Otherwise, looks good to me.

2023-02-01 18:02 UTC, dlongley approved these changes
Thanks! Approving w/suggestions.

2023-02-01 18:02 UTC, dlongley commented on spec/index.html
> +take large amounts of compute time. The algorithm has a mechanism to detect
```suggestion
take large amounts of compute time to canonize. The algorithm has a mechanism to detect
```

2023-02-01 18:02 UTC, dlongley commented on spec/index.html
> +attacker sends a poisoned Dataset might be different from system to system.
```suggestion
attacker sends a poisoned dataset might be different from system to system.
```

2023-02-01 18:02 UTC, dlongley commented on spec/index.html
> +in this algorithm.
```suggestion
utilizes this canonicalization mechanism should have a backup canonicalization
mechanism, such as JCS, or employ other mitigations, such as schema-based
validation, ready in the event that an unrecoverable flaw is found in this algorithm.
```

2023-02-01 22:51 UTC, gkellogg requested changes
Along with @dlongley's suggestions, I added `data-number="70"` to reference the driving issue.

2023-02-01 22:51 UTC, gkellogg commented on spec/index.html
> +    <p class="issue" title="Dataset structure might reveal information">
```suggestion
    <p class="issue" data-number="70" title="Dataset structure might reveal information">
```

2023-02-01 22:51 UTC, gkellogg commented on spec/index.html
> +    <p class="issue" title="Attackers can construct poison Datasets">
Adding `data-number:

```suggestion
    <p class="issue" data-number="70" title="Attackers can construct poison datasets">
```

2023-02-01 22:51 UTC, gkellogg commented on spec/index.html
> +    <p class="issue" title="Formal verification of algorithm is incomplete">
```suggestion
    <p class="issue" data-number="70" title="Formal verification of algorithm is incomplete">
```

2023-02-01 23:12 UTC, msporny commented on spec/index.html
> +    <p class="issue" title="Attackers can construct poison datasets">
```suggestion
    <p class="issue" data-number="70" title="Attackers can construct poison datasets">
```

2023-02-01 23:14 UTC, gkellogg approved these changes

2023-02-02 02:31 UTC, yamdan approved these changes
Thank you @msporny, I will give it a shot on adding something in the section of Selective Disclosure Schemes later; I think not only graph structure but also partial information of the literals could been leaked via canonical labels (or orders), as @dlongley already mentioned in #4 and #8.

2023-02-02 04:18 UTC, TallTed commented on spec/index.html
> +mechanism, such as JCS, or employ other mitigations, such as schema-based
```suggestion
mechanism, such as JCS, or other mitigations to employ, such as schema-based
```

2023-02-02 19:12 UTC, peacekeeper approved these changes
Thanks for moving this forward!

2023-02-04 23:46 UTC, gkellogg commented
@msporny ready to merge?

2023-02-05 15:24 UTC, msporny commented
> @msporny ready to merge?

Yep, I think we got everyone's change requests in. Please merge at your leisure. :)

2023-02-05 20:59 UTC, merged